name: Build and Push Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # v1.0.0 과 같은 태그가 푸시될 때 실행

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # GHCR에 이미지를 푸시하기 위한 권한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 이미지에 사용할 메타데이터(태그 등)를 생성
      # main 푸시 -> 커밋 해시 태그, v* 태그 푸시 -> 버전 태그
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Docker Buildx 설정 (캐싱)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker 이미지 빌드 및 GHCR에 푸시 (캐시 사용)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
